service: bydelsfakta-api

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  environment:
    METADATA_API_URL: ${ssm:/dataplatform/metadata-api/url}
    STAGE: ${self:provider.stage}
  iamManagedPolicies:
    - Fn::Join:
      - ':'
      - - 'arn:aws:iam:'
        - Ref: AWS::AccountId
        - 'policy/bydelsfakta-api-policy'
plugins:
  - serverless-aws-documentation
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-scriptable-plugin
package:
  exclude:
    - "./**"
  include:
    - main.py

functions:
  get_dataset: ${file(serverless/functions/get_dataset.yaml)}

custom:
  scriptHooks:
    after:deploy:finalize: make put-parameter
  documentation:
    title: ${self:service}
    version: 0.1.1
    summary: ${self:service} API
    description: Fetch bydelsfakta.
    models:
      - ${file(./serverless/models/Response.yaml)}
      - ${file(./serverless/models/awsError.yaml)}
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
    slim: true
