frameworkVersion: ">=3.38.0 <4.0.0"

service: bydelsfakta-api

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  timeout: 29
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  environment:
    METADATA_API_URL: ${ssm:/dataplatform/shared/api-gateway-url}/metadata
    STAGE: ${self:provider.stage}
    GIT_REV: ${git:branch}:${git:sha1}
  logRetentionInDays: 90
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
        - 'arn:aws:iam::${aws:accountId}:policy/bydelsfakta-api-policy'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}

plugins:
  - serverless-better-credentials # must be first
  - "@kakkuk/serverless-aws-apigateway-documentation"
  - serverless-plugin-git-variables
  - serverless-prune-plugin
  - serverless-python-requirements

package:
  patterns:
    - '!**/*'
    - bydelsfakta_api/*.py

functions:
  get_dataset: ${file(serverless/functions/get_dataset.yaml)}

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}

custom:
  documentation:
    title: ${self:service}
    version: 0.1.1
    summary: ${self:service} API
    description: Fetch bydelsfakta.
    models:
      - ${file(./serverless/models/Response.yaml)}
      - ${file(./serverless/models/awsError.yaml)}
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  exportGitVariables: false
