version = 0.1

[dev.deploy.parameters]
stack_name = "bydelsfakta-api"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

[prod.deploy.parameters]
stack_name = "bydelsfakta-prod-api"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
